### ISSUE TITLE
Pokemon object height

### ISSUE THREAD

**Issue by ylmonkey** [arnavb/pypokedex#27]
What unit is the height of a pokemon supposed to be? it's just a number and I can't seem to convert it to something readable.

**Comment by arnavb** [comment]
Hi, as mentioned in the [documentation](https://github.com/arnavb/pypokedex#member-variables):

> height (int): Contains the height of the current Pokemon in decimeters (see veekun/pokedex#249).

So while the choice of unit is unusual, you can divide it by 10 to get the Pokemon's height in meters.
