### ISSUE TITLE
Is it possible to get only the hp of a pokemon?

### ISSUE THREAD

**Issue by OmyDaGreat** [arnavb/pypokedex#30]
When I use p.base_stats, it shows all of the base stats of the pokemon. However, is it possible to only return the HP of the pokemon? I tried p.hp, but it returned an error.

**Comment by emboarger** [comment]
p.base_stats.hp returns the hp only

**Comment by arnavb** [comment]
@emboarger Yep! That's correct. For the sake of completeness, here's a snippet showing that:

```python
import pypokedex

p = pypokedex.get(name="garchomp")

print(p.base_stats.hp) # >>> 108 
```
