### ISSUE TITLE
gen XI support

### ISSUE THREAD

**Issue by turtle72** [arnavb/pypokedex#32]
Is support for pokemon s/v in the works?

**Comment by arnavb** [comment]
Hey @turtle72, looks like PokeAPI has support for Gen 9 now (and so does this library by extension); see this example snippet:

```python
import pypokedex

p = pypokedex.get(name="Sprigatito")

print(p.base_stats)
# >>> BaseStats(hp=40, attack=61, defense=54, sp_atk=45, sp_def=45, speed=65)
```
