### ISSUE TITLE
Should include more data- Base EXP gain, EXP growth type

### ISSUE THREAD

**Issue by Butternubbs** [arnavb/pypokedex#5]
This is a very useful database! It would be helpful if a couple more values could be included...
-The base EXP earned from defeating the specified Pokémon
(https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_effort_value_yield)
-The formula used to tell how much EXP a Pokémon needs to level-up
(https://bulbapedia.bulbagarden.net/wiki/Experience#Relation_to_level)

**Comment by arnavb** [comment]
Well the first should be relatively easy to add, the second would require more effort. I'll have to look into both in more detail and see the level of PokeAPI support for each.

**Comment by arnavb** [comment]
I've added support for the exp yield in fbc26c9fabd1dfea396e6c98759f82fd143faae9. I doubt I will implement the other though.
